class Command:
    SIGNUP = 'signup'
    LOGIN = 'login'
    POST = 'post'
    FOLLOW = 'follow'
    REPLY = 'reply'
    UPVOTE_FEED = 'upvote-feed'
    DOWNVOTE_FEED = 'down-feed'
    UPVOTE_COMMENT = 'upvote-comment'
    DOWNVOTE_COMMENT = 'downvote-comment'
    NEWS_FEED = 'newsfeed'
